anasayfa/urls.py
from django.urls import path

from . import views

app_name = 'anasayfa'
urlpatterns = [
    path('', views.AnaSayfa.as_view(), name='anasayfa'),
    path('ziyaretci-defteri/', views.ZiyaretView.as_view(), name='ziyaret'),
    path('yasal-uyarı/', views.YasalView.as_view(), name='copyright'),
    path('dokumanlar/', views.DokumanListView.as_view(), name='dokumanlar'),
    path('iletisim/', views.IletisimView.as_view(), name='iletisim'),
    path('cok-satanlar/', views.cok_satanlar, name='cok_satanlar'),
    #path('deneme/', views.deneme, name='deneme'),
    #path('dokumanlar/<slug:slug>/.docx/', views.DokumanListView.as_view(), name='dokuman-detail'),
    path('genel/<slug:slug>/', views.GenelDetailView.as_view(), name='genel-detail'),
    #path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    #path('<int:question_id>/vote/', views.vote, name='vote'),
]

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

kitap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap

from orders.views import load_cities

from accounts.views import TeacherSignUpView, UserUpdateView, SignUpView, UyelikView
from anasayfa.sitemaps import AnaCategorySitemap, ProductSitemap, StaticViewSitemap, GenelSitemap

sitemaps = {
	'kategoriler' : AnaCategorySitemap,
	'urunler': ProductSitemap,
	'statikler': StaticViewSitemap,
	'genel': GenelSitemap,
}

handler404 = 'anasayfa.views.view_404'

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('anasayfa.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    #path('accounts/signup/student/', StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', TeacherSignUpView.as_view(), name='teacher_signup'),
	#path('accounts/turnuva/', turnuva, name='turnuva'),
	
	path('google68c54442c46469eb.html', TemplateView.as_view(template_name="google68c54442c46469eb.html")),
	#path('t4qt79m922kcpzkf7tuwn3mmebsdva.html', TemplateView.as_view(template_name="t4qt79m922kcpzkf7tuwn3mmebsdva.html")),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", content_type ="text/plain")),
	path('sitemap.xml/', sitemap, {'sitemaps':sitemaps}),
	
	
	path('uyelik/', UyelikView.as_view(), name = 'uyelik'),
	path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),
		
	url(r'^settings/account/$', UserUpdateView.as_view(), name='my_account'),
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
        name='password_change_done'),
	
	path('ajax/load-cities/', load_cities, name='ajax_load_cities'),  # <-- this one here
	
	path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('shop/', include('shop.urls')),
	path('mesaj/', include('mesaj.urls')),
	
	
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
	url(r'^siparislerim/$', views.siparislerim, name='siparisler'),
	path('tarih/', views.tarih, name='tarih'),
	url(r'^siparisler/$', views.tum_siparisler, name='siparislerin_hepsi'),
	path('siparisler/<int:sayi>/', views.tum_siparisler_filtre, name='siparislerin_hepsi_filtre'),
	path('istatistikler/', views.istatistikler, name='istatistikler'),
	path('istatistikler/<int:gun>/', views.istatistik, name='istatistik'),
	url(r'^siparis-ekle/$', views.siparis_ekle, name='siparis-ekle'),
	path('<int:id>/siparisi-duzenle/', views.siparis_duzenle, name="siparis-duzenle"),
	path('<int:id>/', views.siparis_detail, name="siparis-detail"),
	path('<int:id>/urun-ekle/', views.siparis_detail_urun_ekle, name="siparis-detail-urun-ekle"),
	
]

cart/models.py
from django.db import models

# Create your models here.
class Kargo(models.Model):
    agırlık1 = models.PositiveIntegerField(default=0)
    agırlık2 = models.PositiveIntegerField(default=1)
    agırlık3 = models.PositiveIntegerField(default=5)
    agırlık4 = models.PositiveIntegerField(default=10)
    agırlık5 = models.PositiveIntegerField(default=20)
    agırlık6 = models.PositiveIntegerField(default=30)
    agırlık7 = models.PositiveIntegerField(default=50)
    agırlık8 = models.PositiveIntegerField(default=70)
    agırlık9 = models.PositiveIntegerField(default=85)
    agırlık10 = models.PositiveIntegerField(default=100)
    agırlık11 = models.PositiveIntegerField(default=125)
    agırlık12 = models.PositiveIntegerField(default=150)
    agırlık13 = models.PositiveIntegerField(default=175)
    agırlık14 = models.PositiveIntegerField(default=200)
    fiyat1 = models.PositiveIntegerField(default=6)
    fiyat2 = models.PositiveIntegerField(default=8)
    fiyat3 = models.PositiveIntegerField(default=10)
    fiyat4 = models.PositiveIntegerField(default=15)
    fiyat5 = models.PositiveIntegerField(default=20)
    fiyat6 = models.PositiveIntegerField(default=30)
    fiyat7 = models.PositiveIntegerField(default=50)
    fiyat8 = models.PositiveIntegerField(default=60)
    fiyat9 = models.PositiveIntegerField(default=70)
    fiyat10 = models.PositiveIntegerField(default=80)
    fiyat11 = models.PositiveIntegerField(default=100)
    fiyat12 = models.PositiveIntegerField(default=150)
    fiyat13 = models.PositiveIntegerField(default=200)
    fiyat14 = models.PositiveIntegerField(default=250)
    bankacılık_bedeli = models.PositiveIntegerField(default=7)
    
    class Meta:
        verbose_name = 'Kargo-Ağırlık Değeri'
        verbose_name_plural = 'Kargo-Ağırlık Değeri'

    def __str__(self):
        return "kargo ağırlık aralıkları"

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 46)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.contrib import messages

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)  # create a new cart object passing it the request object 
    product = get_object_or_404(Product, id=product_id) 
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
        messages.success(request, 'Ürün sepete eklenmiştir.')
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Sepetiniz
{% endblock %}

{% block content %}
{% include 'includes/messages.html' %}
{% with totail_items=cart|length %}
  <h4 class = "table-bordered bg-success text-white text-center mb-0 mt-3 py-1 siparis-basligi">
  {% if cart|length > 0 %}
	Sepetiniz
  {% else %}
    Sepetiniz boş!
  {% endif %}
{% endwith %}
  </h4>
<table class="table table-sm table-hover table-bordered table-responsive-sm siparis-tablo">
  <thead >
    <tr>
      <th scope="col">Ürün</th>
      <th scope="col">Miktar</th>
      <th scope="col">Sil</th>
	  {% if user.is_superuser %}
	  <th scope="col">Ağırlık</th>
	  {% endif %}
	  <th scope="col">Birim Fiyat</th>
	  <th scope="col">Toplam Fiyat</th>
    </tr>
  </thead>
  <tbody>
  {% for item in cart %}
  {% with product=item.product  %}
  <tr>
    <td>{{ product.name }}</td>
    <td>
      <form action="{% url 'cart:cart_add' product.id %}" method="post" class = "form-inline">
        {% csrf_token %}
        {{ item.update_quantity_form.quantity }}
        {{ item.update_quantity_form.update }}
        <button type="submit" class="guncelle btn btn-sm btn-primary py-0">Güncelle</button>
      </form>
    </td>
    <td>
      <a class = "btn btn-danger btn-sm py-0" href="{% url 'cart:cart_remove' product.id %}">Kaldır</a>
    </td>
	{% if user.is_superuser %}
	<td>{{ item.total_agırlık }} desi</td>
	{% endif %}
    <td>{{ item.price }} TL</td>
    <td>{{ item.total_price }} TL</td>
  </tr>
{% endwith %}
{% endfor %}

  <tr>
    <td><b>Ürünlerin Toplam Fiyatı</b></td>
    <td colspan="{% if user.is_superuser %}4{% else %}3{% endif %}"></td>
    <td colspan="num"><b>{{ cart.get_total_price }} TL</b></td>
  </tr>
  <tr>
    <td><b>Kargo ücreti</b></td>
    <td colspan="{% if user.is_superuser %}4{% else %}3{% endif %}"></td>
    <td colspan="num"><b>{{ cart.get_total_kargo }} TL</b></td>
  </tr>
    <tr>
    <td><b>Toplam</b></td>
    <td colspan="{% if user.is_superuser %}4{% else %}3{% endif %}"></td>
    <td colspan="num"><b>{{ cart.get_total_bedel }} TL</b></td>
  </tr>
  </tbody>
</table>
<div class="text-right">
  <a href="{% url 'anasayfa:anasayfa' %}" class="btn btn-info mb-1">Alışverişe Devam</a>
  <a href="{% if request.user.is_authenticated%}{% url 'orders:order_create' %} {% else %} {% url 'uyelik' %}{% endif %}" class="btn btn-success mb-1">Tamamla</a>
</div>
{% endblock %}