cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

kitap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap

from orders.views import load_cities

from accounts.views import TeacherSignUpView, UserUpdateView, SignUpView, UyelikView
from anasayfa.sitemaps import AnaCategorySitemap, ProductSitemap, StaticViewSitemap, GenelSitemap

sitemaps = {
	'kategoriler' : AnaCategorySitemap,
	'urunler': ProductSitemap,
	'statikler': StaticViewSitemap,
	'genel': GenelSitemap,
}

handler404 = 'anasayfa.views.view_404'

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('anasayfa.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    #path('accounts/signup/student/', StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', TeacherSignUpView.as_view(), name='teacher_signup'),
	#path('accounts/turnuva/', turnuva, name='turnuva'),
	
	path('google68c54442c46469eb.html', TemplateView.as_view(template_name="google68c54442c46469eb.html")),
	#path('t4qt79m922kcpzkf7tuwn3mmebsdva.html', TemplateView.as_view(template_name="t4qt79m922kcpzkf7tuwn3mmebsdva.html")),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", content_type ="text/plain")),
	path('sitemap.xml/', sitemap, {'sitemaps':sitemaps}),
	
	
	path('uyelik/', UyelikView.as_view(), name = 'uyelik'),
	path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),
		
	url(r'^settings/account/$', UserUpdateView.as_view(), name='my_account'),
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
        name='password_change_done'),
	
	path('ajax/load-cities/', load_cities, name='ajax_load_cities'),  # <-- this one here
	
	path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('shop/', include('shop.urls')),
	path('mesaj/', include('mesaj.urls')),
	
	
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
	path('<str:sayi>/', views.product_filter_list, name="product_list__filter"),
    url(r'^kategoriler/(?P<category_slug>[-\w]+)/$', views.category_product_list, name='product_list_by_category'),
	path('kategoriler/<slug:category_slug>/<str:sayi>/', views.category_product_filter_list, name="product_list__filter_by_category"),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/nasil-uygulanir/$', views.product_detail_nasil_uygulanir, name='nasil'),
]

shop/models.py
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField


STATUS_CHOICES = (
	('a', 0),
('b', 10),
    ('c', 15),
    ('d', 20),
    ('e', 25),
	('f', 30),
	('g', 35),
	('h', 40),
	('i', 45),
)

SAYFA_SAYISI = (
	('a', 0),
	('a', 1000),
    ('b', 1500),
	('c', 2500),
)

BUTTON_RENKLERİ = (

	("btn-primary", "mavi"),
	("btn-secondary", "gri"),
	("btn-success", "yeşil"),
	("btn-danger", "kırmızı"),
	("btn-warning", "turuncu"),
	("btn-info", "açık mavi"),
	("btn-light", "ince beyaz"),
	("btn-dark", "koyu siyah"),
	("btn-white", "kalın beyaz"),
	("btn-link", "sadece mavi link"),

)

class AnaCategory(models.Model):
	name = models.CharField("kategori adı", max_length=150, db_index=True)
	slug = models.SlugField("internet adresi",max_length=150, unique=True ,db_index=True, help_text = "Burası yalnızca site-dizaynı için. Dokunmayınız!")
	sayfa_durumu = models.BooleanField("Sayfa Sayısı Var mı?", help_text = "1500-2500 gibi sayfa sayısı varsa işaretlenecek", default = False,)
	bireysel_mi = models.BooleanField("Bireysel mi", help_text = "Öğrencilerle beraber oynanMAyacaksa işaretlenecek!!!", default = False,)
	sadece_madalyalı_mı = models.BooleanField("Sadece Madalya mı", default = False, help_text = "Herhangi bir oyun olmaksızın bir kategori ise işaretlenecek Örneğin; sadece madalya için")
	sıralama_sayısı = models.PositiveIntegerField("Sıralama Sayısı")
	aktif = models.BooleanField("Aktif mi?", help_text="Sitede görünmesini istiyorsanız işaretleyiniz!!!", default = False)
	indirim_miktarı = models.PositiveIntegerField("İndirim miktarı", default = 0)
	arka_plan_renk = models.CharField('Anakategori arka plan rengi', max_length=50, choices=BUTTON_RENKLERİ, default = "btn-primary")
	
	class Meta:
		ordering = ('sıralama_sayısı', )
		verbose_name = 'Ana-Kategori'
		verbose_name_plural = 'Ana-Kategoriler'
	
	def __str__(self):
		return self.name
	
	def get_absolute_url(self):
		return reverse('shop:product_list_by_category', args=[self.slug])
    
	

class TekliResim(models.Model):
	isim = models.CharField("resim adı", max_length=100)
	image1 = models.ImageField("resim")
	
	def __str__(self):
		return self.isim
		
	class Meta:
		ordering = ('isim', )
		verbose_name = 'Resim'
		verbose_name_plural = 'Resimler'
		
class Resim(models.Model):
	isim = models.CharField("resim adı", max_length=100)
	resimler = models.ManyToManyField(TekliResim, verbose_name = "resimler", blank=True)
	sıralama_sayısı = models.PositiveIntegerField("Sıralama Sayısı", default = 0)

	class Meta:
		ordering = ('sıralama_sayısı', 'isim')
		verbose_name = 'Resim-Grubu'
		verbose_name_plural = 'Resim-Grupları'

	def __str__(self):
		return self.isim
	

class Category(models.Model):
    ana_kategori = models.ForeignKey(AnaCategory, on_delete=models.CASCADE, verbose_name = "Ana Kategori", related_name = "altkategoriler")
    name = models.CharField("kategori adı", max_length=150, db_index=True)
    slug = models.SlugField("internet adresi",max_length=150, unique=True ,db_index=True)
    image1 = models.ImageField("Küçültülmüş Kategori Resmi", blank=True, null = True)
    image2 = models.ImageField("Gerçek Kategori Resmi", blank=True, null = True)
    nasıl_uygulanır_resimleri = models.ForeignKey(Resim, on_delete=models.CASCADE, blank = True, null = True,verbose_name = "Nasıl Uygulanır Resimleri", related_name= "nasil")
    odul_buttonu_resimleri = models.ForeignKey(Resim, on_delete=models.CASCADE, blank = True, null = True, verbose_name = "Kişiye özel Ödül Butonu Resimleri", related_name = 'odul')
    sayi = models.PositiveIntegerField("Sıralama Sayısı")
    madalyalı_mı = models.BooleanField("Madalyalı mı", default = True)
    sayfa_sayısı = models.CharField('sayfa sayısı', max_length=1, choices=SAYFA_SAYISI)
    aktif = models.BooleanField("Aktif mi?", help_text="Sitede görünmesini istiyorsanız işaretleyiniz!!!", default = False)
    

    class Meta:
        ordering = ('sayi',)
        verbose_name = 'Kategori'
        verbose_name_plural = 'Kategoriler'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name = "kategori")
    name = models.CharField("ürün adı", max_length=100, db_index=True)
    slug = models.SlugField("internet adresi",max_length=100, db_index=True)
    description = RichTextField("Ürün açıklaması", blank=True)
    price = models.DecimalField("gerçek fiyat", max_digits=10, decimal_places=2)
    degisiklik = models.IntegerField("degisiklik", default = 0)
    agırlık = models.FloatField("Ağırlık",default = 0)
    ogrenci_sayisi = models.CharField(max_length=1, choices=STATUS_CHOICES)
    anasayfada_gosterilsin_mi = models.BooleanField("AnaSayfada gösterilsin mi?", default = False, help_text = "Anasayfada gösterilmesi istenen ürünler için işaretlenecektir.")
    aktif = models.BooleanField("Aktif mi?", help_text="Sitede görünmesini istiyorsanız işaretleyiniz!!!", default = False)
    sıralama_sayısı = models.PositiveIntegerField("Anasayfa Sıralama Sayısı", default = 0)
    
    class Meta:
        ordering = ('sıralama_sayısı', )
        index_together = (('id', 'slug'),)
        verbose_name = 'Ürün'
        verbose_name_plural = "Ürünler"

    def __str__(self):
        return self.name
    
    #def pahalı_fiyat_hesapla(self):
     #   self.pahalı_fiyat = self.price + self.category.ana_kategori.indirim_miktarı
      #  self.save()

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])
	
    def get_nasil_url(self):
        return reverse('shop:nasil', args=[self.id, self.slug])
	
    def pahalı_fiyat_hesapla(self):
        return self.category.ana_kategori.indirim_miktarı + self.price + self.degisiklik
        

	

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, AnaCategory
from cart.forms import CartAddProductForm


def product_list(request):
    categories = AnaCategory.objects.filter(aktif = True).order_by('sıralama_sayısı')
    products1 = Product.objects.filter(category__ana_kategori__aktif = True, category__aktif = True, aktif = True, ogrenci_sayisi = "e").order_by("category__sayi")
    products2 = Product.objects.filter(category__ana_kategori__aktif = True, category__aktif = True, aktif = True, ogrenci_sayisi = "a").order_by("category__sayi")

    ogrenci_sayısı = (
		('b', 10),
		('c', 15),
		('d', 20),
		('e', 25),
		('f', 30),
		('g', 35),
		('h', 40),
		('i', 45),
    )	
	

    context = {
		'ogrenci_sayısı': ogrenci_sayısı,
        'categories': categories,
        'products1': products1,
        'products2': products2,
    }
    return render(request, 'shop/product/list.html', context)

def product_filter_list(request, sayi):
    categories = AnaCategory.objects.filter(aktif = True).order_by('sıralama_sayısı')
    products1 = Product.objects.filter(category__ana_kategori__aktif = True, category__aktif = True, ogrenci_sayisi = sayi, aktif = True).order_by("category__sayi")

    ogrenci_sayısı = (
		('b', 10),
		('c', 15),
		('d', 20),
		('e', 25),
		('f', 30),
		('g', 35),
		('h', 40),
		('i', 45),
    )	


    context = {
		'ogrenci_sayısı': ogrenci_sayısı,
        'categories': categories,
        'products1': products1
    }
    return render(request, 'shop/product/list.html', context)
	
def category_product_list(request, category_slug):
    category = get_object_or_404(AnaCategory, slug=category_slug, aktif = True)
    if not category.bireysel_mi:
        products = Product.objects.filter(category__ana_kategori=category, category__aktif = True, aktif = True,  ogrenci_sayisi = "c").order_by("category__sayi")
    else:
        products = Product.objects.filter(category__ana_kategori=category, category__aktif = True, aktif = True).order_by("category__sayi")
    categories = AnaCategory.objects.exclude(slug = category_slug).filter(aktif = True).order_by('sıralama_sayısı')

    ogrenci_sayısı = (
		('b', 10),
		('c', 15),
		('d', 20),
		('e', 25),
		('f', 30),
		('g', 35),
		('h', 40),
		('i', 45),
    )

    context = {
		'ogrenci_sayısı': ogrenci_sayısı,
        'category': category,
        'products': products,
		'categories': categories
    }
    return render(request, 'shop/product/category_detail.html', context)

def category_product_filter_list(request, category_slug, sayi):
    category = get_object_or_404(AnaCategory, slug=category_slug, aktif = True)
    products = Product.objects.filter(category__ana_kategori=category, ogrenci_sayisi = sayi, aktif = True, category__aktif = True).order_by("category__sayi")
    categories = AnaCategory.objects.exclude(slug = category_slug).filter(aktif =True).order_by('sıralama_sayısı')

    ogrenci_sayısı = (
		('b', 10),
		('c', 15),
		('d', 20),
		('e', 25),
		('f', 30),
		('g', 35),
		('h', 40),
		('i', 45),
    )

    context = {
		'ogrenci_sayısı': ogrenci_sayısı,
        'category': category,
        'products': products,
		'categories': categories
    }
    return render(request, 'shop/product/category_detail.html', context)



def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, category__aktif = True, aktif = True)
    products = Product.objects.exclude(ogrenci_sayisi = product.ogrenci_sayisi).filter(category__ana_kategori = product.category.ana_kategori, category = product.category, category__aktif = True, aktif = True).order_by('ogrenci_sayisi')
    print("")
    print(products)
    print("")
    cart_product_form = CartAddProductForm()
    context = {
		'products': products,
        'product': product,
        'form': cart_product_form
    }
    return render(request, 'shop/product/detail.html', context)

def product_detail_nasil_uygulanir(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, category__aktif = True, aktif = True)
    context = {
        'product': product,
    }
    return render(request, 'shop/product/nasil-detail.html', context)

	

shop/templates/shop/product/category_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{category.name}} {% endblock %}
{% block metalar %}
		<meta name="description" content="{{category.name}}'e ait ürünlerine bu sayfadan erişebilirsiniz.">
		<meta name="keywords" content="{{category.name}}">
{% endblock %}

{% block sharethis %}
	<script async src="https://platform-api.sharethis.com/js/sharethis.js#property=5d72714eab6f1000123c810c&product=sticky-share-buttons"></script>
	<script type='text/javascript' src='https://platform-api.sharethis.com/js/sharethis.js#property=5d72714eab6f1000123c810c' async='async'></script>
{% endblock %}

{% block content %} 
 <div class = "row justify-content-md-center justify-content-sm-center justify-content-lg-center">
 
 <div class = "col-md-8 col-sm-12">
 <div class="card-header text-center text-white bg-success mt-2 border border-white">
    <h4>{{category.name}}</h4>
  </div>
  
<div class="card text-center border border-white">
  <div class="card-header">
    <ul class="nav nav-pills card-header-pills">
	{% if not category.bireysel_mi %}
	  <li class="nav-item dropdown ml-2">
		<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Öğrenci Sayısı</a>	
		<div class="dropdown-menu">
      {% for sayi in ogrenci_sayısı%}
		<a class="dropdown-item" href="{% url 'shop:product_list__filter_by_category' category.slug sayi.0 %}">{{sayi.1}}</a>
		{% endfor %}
		</div>
	  </li>   
	 {% endif %} 
	  
      <li class="nav-item dropdown ml-2">
		<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Diğer Kategoriler</a>
		<div class="dropdown-menu">
		<div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url 'shop:product_list'%}">Hepsi</a>
		{% for category in categories%}
		<a class="dropdown-item" href="{{ category.get_absolute_url}}">{{category.name}}</a>
		{% endfor %}
		</div>
	  </li>

	  
    </ul>
  </div>
</div>
 <div class = "row ">
  {% for product in products %}
   <div class = "col-md-6 col-sm-6 mt-2 mb-2">
       <div class="card text-center border border-white">  
         <a href = "{{product.get_absolute_url }}">{% if product.category.image1 %}
		   <img class="card-img-top img-responsive" src="{{product.category.image1.url}}" alt="{{product.name}}">{% endif %}
		 </a>
		         <div class="card-footer py-1 px-0">
                <small class="font-weight-bold">{{product.price}} TL</small>
	  {% if not product.category.ana_kategori.indirim_miktarı == 0 %}
	  <small class="text-muted"><s>{{product.pahalı_fiyat_hesapla}} TL </s></small>
	  {% endif %}
        </div>
         <div class="card-body px-0 py-0">
		   	<div class="btn-group btn-group-sm justify-content-between w-100 mb-1" role="group" aria-label="Basic example">
  {% if not product.category.ana_kategori.sadece_madalyalı_mı %}
	<a href = "{{product.get_nasil_url}}" type="button" class="btn btn-primary">Nasıl Uygulanır?</a>
    {% endif %}
	<a href = "{{product.get_absolute_url}}" type="button" class="btn btn-success">Ürünü İncele</a>
</div>
           <h5 class="card-title urun-basligi my-auto">{{product.name}}</h5>
         </div>  

       </div>
   </div>
  {% endfor %}
</div>,  
 </div>,
 </div>
{% endblock %}

shop/templates/shop/product/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{product.name}}
{% endblock %}

{% block sharethis %}
	<script async src="https://platform-api.sharethis.com/js/sharethis.js#property=5d72714eab6f1000123c810c&product=sticky-share-buttons"></script>
	<script type='text/javascript' src='https://platform-api.sharethis.com/js/sharethis.js#property=5d72714eab6f1000123c810c' async='async'></script>
{% endblock %}

{% block metalar %}
		<meta name="description" content="{{product.name}}'e ait bilgilere bu sayfamızdan erişebilirsiniz.">
		<meta name="keywords" content="{{product.name}}">
{% endblock %}

{% block content %}
<div class="row justify-content-md-center justify-content-sm-center justify-content-lg-center">
<div class = "col-md-5 col-lg-5 col-sm-6 mt-3">
<div class="card text-center border border-white">
  <a href = "{% if product.category.image2 %}{{product.category.image2.url}}{% endif %}"><img class="card-img-top img-responsive detail-resim" src="{{product.category.image1.url}}" alt="Card image cap"></a>
    <div class="card-footer py-1 bg-light">
          <small class="font-weight-bold">{{product.price}} TL</small>
	  {% if not product.category.ana_kategori.indirim_miktarı == 0 %}
	  <small class="text-muted"><s>{{product.pahalı_fiyat_hesapla}} TL </s></small>
	  {% endif %}
    </div>
  <div class="card-body px-0 py-0">
  <div class="btn-group btn-group-sm justify-content-between w-100 mb-1" role="group" aria-label="Basic example">
  <a href = "{{product.category.ana_kategori.get_absolute_url}}" type="button" class="btn btn-warning">Kategorinin Diğer Ürünleri</a>
  {% if not product.category.ana_kategori.sadece_madalyalı_mı %}
  <a href = "{{product.get_nasil_url}}" type="button" class="btn btn-primary btn-sm">Nasıl Uygulanır?</a>
  {% endif %}
  
</div>
  {% if product.category.ana_kategori.sayfa_durumu %}
   
    <div class="mx-auto mb-1 dropdown">
      <button class="btn btn-light btn-sm d-inline dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Öğrenci Sayısı: {{product.get_ogrenci_sayisi_display}}
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        {% for product in products %}
        <a class="dropdown-item " href="{{product.get_absolute_url}}"> {{product.get_ogrenci_sayisi_display}}</a>
        {% endfor %}
      </div>
    </div>
  
	
  
  {% endif %}
    
	<form class = "form-inline justify-content-center" action="{% url 'cart:cart_add' product.id %}" method="post">
    {% csrf_token %}
      {% include 'includes/form3.html' %}
      <input type="submit" value="Sepete Ekle" class="btn btn-sm btn-primary ml-2">
    </form>
  </div>

  
</div>
</div>
<div class = "col-md-4 col-lg-4 col-sm-6 mt-3">
	<div class = "car-header bg-danger text-white text-center py-1 rounded">Ürün içeriği</div>
	<div class="card-text text-left mt-2 ml-2 urun-basligi">{{product.description|safe}}</div>
</div>
</div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Ürünler {% endblock %}

{% block content %}
<div class="card-header text-center text-white bg-success mt-2 border border-white"><h4>MAĞAZAMIZ</h4></div>
<div class="card text-center border border-white">
  <div class="card-header">
    <ul class="nav nav-pills card-header-pills">	  
	  <li class="nav-item dropdown ml-2">
		<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Öğrenci Sayısı</a>
		<div class="dropdown-menu">
      {% for sayi in ogrenci_sayısı%}
		<a class="dropdown-item" href="{% url 'shop:product_list__filter' sayi.0 %}">{{sayi.1}}</a>
		{% endfor %}
		</div>
	  </li>   
	  
      <li class="nav-item dropdown ml-2">
		<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Kategoriler</a>
		<div class="dropdown-menu">
		{% for category in categories%}
		<a class="dropdown-item" href="{{ category.get_absolute_url }}">{{category.name}}</a>
		{% endfor %}
		</div>
	  </li>   
    </ul>
  </div>
</div> 
 
 <div class = "row">
  {% for product in products1 %}
   <div class = "col-md-3 col-sm-4 mt-2 mb-2">
       <div class="card text-center h-100 border border-white">  
         <a href = "{{product.get_absolute_url }}">{% if product.category.image1 %}
		   <img class="card-img-top img-responsive" src="{{product.category.image1.url}}" alt="{{product.name}}">{% endif %}
		 </a>
		  <div class="card-footer py-1 px-0">
             <small class="font-weight-bold">{{product.price}} TL</small>
	  {% if not product.category.ana_kategori.indirim_miktarı == 0 %}
	  <small class="text-muted"><s>{{product.pahalı_fiyat_hesapla}} TL </s></small>
	  {% endif %}
        </div>
         <div class="card-body px-0 py-0">
		   	<div class="btn-group btn-group-sm justify-content-between w-100 mb-1" role="group" aria-label="Basic example">
  {% if not product.category.ana_kategori.sadece_madalyalı_mı %}
	<a href = "{{product.get_nasil_url}}" type="button" class="btn btn-primary">Nasıl Uygulanır?</a>
    {% endif %}
	<a href = "{{product.get_absolute_url}}" type="button" class="btn btn-success">Ürünü İncele</a>
</div> 
           <h5 class="card-title urun-basligi my-auto">{{product.name}}</h5>
           <p class="card-text">{{product.content}}</p>
         </div>  
       
       </div>
   </div>
  {% endfor %}
  
    {% for product in products2 %}
   <div class = "col-md-3 col-sm-4 mt-2 mb-2">
       <div class="card text-center h-100 border border-white">  
         <a href = "{{product.get_absolute_url }}">{% if product.category.image1 %}
		   <img class="card-img-top img-responsive" src="{{product.category.image1.url}}" alt="{{product.name}}">{% endif %}
		 </a>
		         <div class="card-footer py-1">
                <small class="font-weight-bold">{{product.price}} TL</small>
	  {% if not product.category.ana_kategori.indirim_miktarı == 0 %}
	  <small class="text-muted"><s>{{product.pahalı_fiyat_hesapla}} TL </s></small>
	  {% endif %}
        </div>
         <div class="card-body">
		   {% if not product.category.ana_kategori.sadece_madalyalı_mı %}
	       <a href = "{{product.get_nasil_url}}" type="button" class="btn btn-primary btn-sm btn-block mb-1">Nasıl Uygulanır</a>
           {% endif %} 
           <h5 class="card-title my-auto urun-basligi">{{product.name}}</h5>
           <p class="card-text">{{product.content}}</p>
         </div>  

       </div>
   </div>
  {% endfor %}
 </div>
{% endblock %}

shop/templates/shop/product/nasil-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{product.name}}-nasıl uygulanır
{% endblock %}

{% block metalar %}
		<meta name="description" content="{{product.name}} ürünün nasıl uygulandığına dair bilgilere bu sayfamızdan erişebilirsiniz.">
		<meta name="keywords" content="{{product.name}} uygulanması">
{% endblock %}

{% block sharethis %}
	<script async src="https://platform-api.sharethis.com/js/sharethis.js#property=5d72714eab6f1000123c810c&product=sticky-share-buttons"></script>
	<script type='text/javascript' src='https://platform-api.sharethis.com/js/sharethis.js#property=5d72714eab6f1000123c810c' async='async'></script>
{% endblock %}

{% block content %}
<div class = "row justify-content-md-center justify-content-sm-center justify-content-lg-center">
	<div class = "col-md-6 col-lg-6 col-sm-8">
		<div class="card mb-3 text-center">
			<div class="card-header bg-danger text-white"><h5><a href = "{{product.get_absolute_url}}" class = "text-white">{{product.name}}</a> <br>NASIL UYGULANIR?</h5></div>
		  {% if product.category.nasıl_uygulanır_resimleri %}
			{% for resim in product.category.nasıl_uygulanır_resimleri.resimler.all %}
				<img src="{{resim.image1.url}}" class="img-fluid img-thumbnail mb-2" alt="{{resim.isim}}">
			{% endfor %}	
		  {% endif %}
  <div class="btn-group btn-group-sm justify-content-between w-100" role="group" aria-label="Basic example">
  <a href = "{{product.category.ana_kategori.get_absolute_url}}" type="button" class="btn btn-warning">Kategorinin Diğer Ürünleri</a>
  <a href = "{{product.get_absolute_url}}" type="button" class="btn btn-success btn-sm">Ürüne Git</a>
  </div>
		</div>
	</div>
</div>
{% endblock %}