cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

kitap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap

from orders.views import load_cities

from accounts.views import TeacherSignUpView, UserUpdateView, SignUpView, UyelikView
from anasayfa.sitemaps import AnaCategorySitemap, ProductSitemap, StaticViewSitemap, GenelSitemap

sitemaps = {
	'kategoriler' : AnaCategorySitemap,
	'urunler': ProductSitemap,
	'statikler': StaticViewSitemap,
	'genel': GenelSitemap,
}

handler404 = 'anasayfa.views.view_404'

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('anasayfa.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    #path('accounts/signup/student/', StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', TeacherSignUpView.as_view(), name='teacher_signup'),
	#path('accounts/turnuva/', turnuva, name='turnuva'),
	
	path('google68c54442c46469eb.html', TemplateView.as_view(template_name="google68c54442c46469eb.html")),
	#path('t4qt79m922kcpzkf7tuwn3mmebsdva.html', TemplateView.as_view(template_name="t4qt79m922kcpzkf7tuwn3mmebsdva.html")),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", content_type ="text/plain")),
	path('sitemap.xml/', sitemap, {'sitemaps':sitemaps}),
	
	
	path('uyelik/', UyelikView.as_view(), name = 'uyelik'),
	path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),
		
	url(r'^settings/account/$', UserUpdateView.as_view(), name='my_account'),
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
        name='password_change_done'),
	
	path('ajax/load-cities/', load_cities, name='ajax_load_cities'),  # <-- this one here
	
	path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('shop/', include('shop.urls')),
	path('mesaj/', include('mesaj.urls')),
	
	
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
	url(r'^siparislerim/$', views.siparislerim, name='siparisler'),
	path('tarih/', views.tarih, name='tarih'),
	url(r'^siparisler/$', views.tum_siparisler, name='siparislerin_hepsi'),
	path('siparisler/<int:sayi>/', views.tum_siparisler_filtre, name='siparislerin_hepsi_filtre'),
	path('istatistikler/', views.istatistikler, name='istatistikler'),
	path('istatistikler/<int:gun>/', views.istatistik, name='istatistik'),
	url(r'^siparis-ekle/$', views.siparis_ekle, name='siparis-ekle'),
	path('<int:id>/siparisi-duzenle/', views.siparis_duzenle, name="siparis-duzenle"),
	path('<int:id>/', views.siparis_detail, name="siparis-detail"),
	path('<int:id>/urun-ekle/', views.siparis_detail_urun_ekle, name="siparis-detail-urun-ekle"),
	
]

orders/models.py
from django.db import models
from shop.models import Product
from accounts.models import User
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from decimal import Decimal
#from phone_field import PhoneField

from cart.models import Kargo

ILLER = [['1', 'Adana'], ['2', 'Adıyaman'], ['3', 'Afyonkarahisar'], ['4', 'Ağrı'], ['5', 'Aksaray'], ['6', 'Amasya'], ['7', 'Ankara'], ['8', 'Antalya'], ['9', 'Ardahan'], ['10', 'Artvin'], ['11', 'Aydın'], ['12', 'Balıkesir'], ['13', 'Bartın'], ['14', 'Batman'], ['15', 'Bayburt'], ['16', 'Bilecik'], ['17', 'Bingöl'], ['18', 'Bitlis'], ['19', 'Bolu'], ['20', 'Burdur'], ['21', 'Bursa'], ['22', 'Çanakkale'], ['23', 'Çankırı'], ['24', 'Çorum'], ['25', 'Denizli'], ['26', 'Diyarbakır'], ['27', 'Düzce'], ['28', 'Edirne'], ['29', 'Elazığ'], ['30', 'Erzincan'], ['31', 'Erzurum'], ['32', 'Eskişehir'], ['33', 'Gaziantep'], ['34', 'Giresun'], ['35', 'Gümüşhane'], ['36', 'Hakkâri'], ['37', 'Hatay'], ['38', 'Iğdır'], ['39', 'Isparta'], ['40', 'İstanbul'], ['41', 'İzmir'], ['42', 'Kahramanmaraş'], ['43', 'Karabük'], ['44', 'Karaman'], ['45', 'Kars'], ['46', 'Kastamonu'], ['47', 'Kayseri'], ['48', 'Kilis'], ['49', 'Kırıkkale'], ['50', 'Kırklareli'], ['51', 'Kırşehir'], ['52', 'Kocaeli'], ['53', 'Konya'], ['54', 'Kütahya'], ['55', 'Malatya'], ['56', 'Manisa'], ['57', 'Mardin'], ['58', 'Mersin'], ['59', 'Muğla'], ['60', 'Muş'], ['61', 'Nevşehir'], ['62', 'Niğde'], ['63', 'Ordu'], ['64', 'Osmaniye'], ['65', 'Rize'], ['66', 'Sakarya'], ['67', 'Samsun'], ['68', 'Şanlıurfa'], ['69', 'Siirt'], ['70', 'Sinop'], ['71', 'Sivas'], ['72', 'Şırnak'], ['73', 'Tekirdağ'], ['74', 'Tokat'], ['75', 'Trabzon'], ['76', 'Tunceli'], ['77', 'Uşak'], ['78', 'Van'], ['79', 'Yalova'], ['80', 'Yozgat'], ['81', 'Zonguldak']]

KARGO_TIPLERI = (
    ('1', 'Kapıda Nakit Ödeme'),
    ('2', 'Kapıda Tek Çekim Kredi Kartı Ödeme'),
    ('3', 'Havale/EFT'),
)

SIPARIS_DURUMLARI = (
    ('1', 'İşlemde'),
    ('2', 'Hazırlanıyor'),
    ('3', 'Kargoya Teslim Edildi'),
	('4', 'İptal'),
)


class Order(models.Model):
    kargo_tipi = models.CharField('Ödeme Tercihiniz:', max_length=10, choices=KARGO_TIPLERI, help_text = "Blabla")
    first_name = models.CharField("Adınız:", max_length=60)
    last_name = models.CharField("Soyadınız:",max_length=60)
    email = models.EmailField()
    address = models.TextField("Adres:")
    phone = models.CharField("Telefon No:", blank=True, help_text='İrtibat Numarası', max_length=20)
    city = models.CharField('Şehir:', max_length=10, choices=ILLER)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField("Ödenme durumu", default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name = "Müşteri", blank = True, null = True)
    siparis_durumu = models.CharField('Sipariş Durumu:', max_length=10, choices=SIPARIS_DURUMLARI, default = "1")
    siparis_notu = models.TextField("Sipariş Notu:", blank = True)
    indirim_tutari = models.PositiveIntegerField("İndirim Miktarı", default=0)
    toplam_urun_tutarı = models.PositiveIntegerField("Ürün bedeli", default=0)
	
    class Meta:
        ordering = ('-created', )
        verbose_name = 'Sipariş'
        verbose_name_plural = "Siparişler"
		

    def __str__(self):
        return 'Sipariş {}'.format(self.id)
		
    #def clean(self):
    #    if not 9 < len(self.phone) < 12:
    #        raise ValidationError({'phone': _('Telefon Numaranız 10 ya da 11 haneli olmalıdır. Örneğin 05321111111 ya da 5321111111')})
			
	
    def get_absolute_url(self):
        return reverse('orders:siparis-detail', kwargs={'id':self.id})
	
    def save(self, *args, **kwargs):
        self.toplam_urun_tutarı = self.get_total_cost()       
        return super(Order, self).save(*args, **kwargs)
		
    def get_siparis_no(self):
        return self.id + 156789
		
    def urun_ekle(self):
        return reverse('orders:siparis-detail-urun-ekle', kwargs={'id':self.id})
	
    def siparis_olustur(self):
        return reverse('orders:siparis-ekle')

    def siparis_duzenle(self):
        return reverse('orders:siparis-duzenle', kwargs={'id':self.id})

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.orderitem_set.all())
	
    get_total_cost.short_description = "Ürünlerin toplam bedeli"
    
    def get_total_kargo(self):
        toplam_agırlık = sum(item.get_agırlık() for item in self.orderitem_set.all())
        kargo = Kargo.objects.first()
        if  kargo.agırlık1 <= toplam_agırlık < kargo.agırlık2:
            return kargo.fiyat1
        if  kargo.agırlık2 <= toplam_agırlık < kargo.agırlık3:
            return kargo.fiyat2
        if  kargo.agırlık3 <= toplam_agırlık < kargo.agırlık4:
            return kargo.fiyat3
        if  kargo.agırlık4 <= toplam_agırlık < kargo.agırlık5:
            return kargo.fiyat4
        if  kargo.agırlık5 <= toplam_agırlık < kargo.agırlık6:
            return kargo.fiyat5
        if  kargo.agırlık6 <= toplam_agırlık < kargo.agırlık7:
            return kargo.fiyat6
        if  kargo.agırlık7 <= toplam_agırlık < kargo.agırlık8:
            return kargo.fiyat7
        if  kargo.agırlık8 <= toplam_agırlık < kargo.agırlık9:
            return kargo.fiyat8
        if  kargo.agırlık9 <= toplam_agırlık < kargo.agırlık10:
            return kargo.fiyat9
        if  kargo.agırlık10 <= toplam_agırlık < kargo.agırlık11:
            return kargo.fiyat10
        if  kargo.agırlık11 <= toplam_agırlık < kargo.agırlık12:
            return kargo.fiyat11
        if  kargo.agırlık12 <= toplam_agırlık < kargo.agırlık13:
            return kargo.fiyat12
        if  kargo.agırlık13 <= toplam_agırlık < kargo.agırlık14:
            return kargo.fiyat13
        if  kargo.agırlık14 <= toplam_agırlık :
            return kargo.fiyat14
	
    get_total_kargo.short_description = "Kargo bedeli"
	
    def get_total_bedel(self):
        return self.get_total_cost() + self.get_total_kargo() + self.banka_bedel()

    get_total_bedel.short_description = "Toplam Tutar"
    
    def get_indirimli_bedel(self):
        return self.get_total_cost() + self.get_total_kargo() + self.banka_bedel() - self.indirim_tutari
	
    get_indirimli_bedel.short_description = "İndirimli Toplam Tutar"
	
    def banka_bedel(self):
        if self.kargo_tipi == "3":
            return 0
        else:
            kargo = Kargo.objects.first()
            return kargo.bankacılık_bedeli
		

    banka_bedel.short_description = "Banka bedeli"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name = "Sipariş")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name = "Ürün")
    price = models.DecimalField("Fiyat", max_digits=10, decimal_places=2, default = 0)
    quantity = models.PositiveIntegerField("Miktar", default=1)
    agırlık = models.FloatField("Ağırlık", default=0)
	
    def __str__(self):
        return self.product.name
	
	
	
    class Meta:
        verbose_name = 'Ürün'
        verbose_name_plural = "Ürünler"

    def get_cost(self):
        return self.price * self.quantity
    
    def get_agırlık(self):
        return self.agırlık * self.quantity
	
    def save(self, *args, **kwargs):
        self.price = self.product.price
        self.agırlık = self.product.agırlık
        return super(OrderItem, self).save(*args, **kwargs)
	

	
	

orders/forms.py
from django import forms
from .models import Order, OrderItem

from shop.models import Product, AnaCategory


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['kargo_tipi','first_name', 'last_name', 'phone', 'email', 'address', 'city', 'siparis_notu']


class OrderItemForm(forms.ModelForm):
	kategori = forms.ModelChoiceField(queryset=AnaCategory.objects.all())
	
	class Meta:
		model = OrderItem
		fields = ['kategori','product', 'quantity']
	
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields['product'].queryset = Product.objects.none()
	
		if 'kategori' in self.data:
			try:
				country_id = int(self.data.get('kategori'))
				self.fields['product'].queryset = Product.objects.filter(category__ana_kategori_id=country_id)
			except (ValueError, TypeError):
				pass  # invalid input from the client; ignore and fallback to empty City queryset
		elif self.instance.pk:
			self.fields['product'].queryset = self.instance.kategori.category_set.product_set

class SiparisForm(forms.ModelForm):
	class Meta:
		model = Order
		fields = ['kargo_tipi','first_name', 'last_name', 'phone', 'email', 'address', 'city', 'siparis_notu', "siparis_durumu", "indirim_tutari", "user"]
		

orders/templates/orders/order/istatistikler.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Istatistikler
{% endblock %}

{% block content %}

<form method = "post" class = "mb-2" action = "{% url 'orders:tarih' %}">
{% csrf_token %}
  <div class="row">
    <div class="col">
	<label for="start">Başlangıç Tarihi:</label>
<input class = "form-control"type="date" id="start" name="bir"
	   value="2019-09-01"
       min="2019-01-01" max="2030-01-01" required>
    </div>
    <div class="col">
      <label for="start">Bitiş Tarihi:</label>
<input class = "form-control" type="date" id="start" name="iki"
	   value="2019-10-01"
       min="2019-01-01" max="2030-01-01" required>
    </div>
	</div>
  <button type="submit" class="btn btn-primary btn-block btn-sm mt-1">Gönder</button>
</form>
<hr>
<div class = "row">
    {% for key, value in gunler.items %}
  <div class = "col-md-4 col-sm-6 col-xs-2 mb-2">
	<a href = "{% url 'orders:istatistik' value %}" class = "btn btn-md btn-outline-secondary btn-block">{{key}}</a>
  </div>
  {% endfor %}
</div>

{% endblock %}

orders/templates/orders/order/siparis-detail-urun-ekle.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}


{% block body %}

<div class="container">
	<div class="row">
		<div class="col-md-9">
			<form method="POST" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}" novalidate>
				{% csrf_token %}
				<h1>{{siparis.firs_name}} {{siparis.last_name}} Siparişine ürün ekleme</h1>
				{{form|crispy}}				
				<input class="btn btn-primary" type="submit" value="Gönder">
			</form>
		</div>
	</div>
</div>

{% endblock %}

{% block javascript %}
<script>
    $("#id_kategori").change(function () {
      var url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
      var countryId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'kategori': countryId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_product").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>
{% endblock %}

orders/templates/orders/order/siparis-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Siparişiniz
{% endblock %}

{% block content %}
{% include 'includes/messages.html' %}
	<div class = "row">
		<div class = "col-md-3 pl-0 mt-0 detailmenu liste">
			<div class="list-group list-group-flush mt-0">
			  {% for order in siparisler %}
				<a href="{{order.get_absolute_url}}" class="list-group-item list-group-item-action list-group-item-info {% if order.id ==  order.id %}active{% endif %}">{{order.first_name}} {{order.last_name}}<small><b>-{{order.get_siparis_durumu_display}}-{{order.created|date}}</b></small></a>
			  {% endfor %}
			</div>
		</div>
		<div class = "col-md-9 icerik tum-siparis-detail">
			<h2 class = "text-center text-danger headline">		
				{{siparis.first_name}} {{siparis.last_name}}
				- <span class = "badge badge-pill badge-warning">{{siparis.get_siparis_durumu_display}}</span>
			</h2>
			<div class = "row">
			<div class = "col-md-6 col-lg-6">
			<h3 class = "text-left text-danger headline">		
				Sipariş Bilgileri			
			</h3>
			<a href = "{{siparis.siparis_duzenle}}" class = "btn btn-warning btn-sm">Siparişi Düzenle</a>
			<a href = "{{siparis.siparis_olustur}}" class = "btn btn-success btn-sm">Yeni Sipariş Oluştur</a>
			<hr>
			<p class = "mb-1"><b>Sipariş Numarası:</b> {{siparis.id}}</p>
			<p class = "mb-1"><b>Ödeme Tercihi:</b> {{siparis.get_kargo_tipi_display}}</p>
			<p class = "mb-1"><b>Email:</b> {{siparis.email}}</p>
			<p class = "mb-1"><b>Telefon No:</b> {{siparis.phone}}</p>
			<p class = "mb-1"><b>Adres:</b> {{siparis.address}}</p>
			<p class = "mb-1"><b>Şehir:</b> {{siparis.get_city_display}}</p>
			<p class = "mb-1"><b>Tarih:</b> {{siparis.created}}</p>
			<p class = "mb-1"><b>Ödeme Durumu:</b> {{siparis.paid}}</p>
			<p class = "mb-1"><b>Kullanıcı:</b> {{siparis.user.username}}</p>
			<p class = "mb-1"><b>Sipariş Durumu:</b> {{siparis.get_siparis_durumu_display}}</p>
			<p class = "mb-1"><b>Sipariş Notu:</b> {{siparis.siparis_notu}}</p>
			<p class = "mb-1"><b>İndirim Miktarı:</b> {{siparis.indirim_tutari}} TL</p>
			<p class = "mb-1"><b>Kargo Tutarı:</b> {{siparis.get_total_kargo}} TL</p>
			<p class = "mb-1"><b>Bankacılık Bedeli:</b> {{siparis.banka_bedel}} TL</p>
			<p class = "mb-1"><b>Toplam Tutar:</b> {{siparis.get_total_bedel}} TL</p>
			<p class = "mb-1"><b>İndirimli Toplam Tutar:</b> {{siparis.get_indirimli_bedel}} TL</p>
			</div>
			<div class = "col-md-6">
				<h3 class = "text-left text-danger headline">		
				Ürün Bilgileri			
				</h3>
				<a href = "{{siparis.urun_ekle}}" class = "btn btn-info btn-sm">Siparişe Ürün Ekle</a>
				<hr>
				{% for urun in siparis.orderitem_set.all %}
					<p class = "mb-1"><b>Ürün adı:</b> <a href = "{{urun.product.get_absolute_url}}">{{urun.product.name}}</a></p>
					<p class = "mb-1"><b>Ürün Birim Fiyatı:</b> {{urun.price}} TL</p>
					<p class = "mb-1"><b>Ürün adedi:</b> {{urun.quantity}}</p>
					<p class = "mb-1"><b>Ürün Toplam Tutarı:</b> {{urun.get_cost}} TL</p>
					<p class = "mb-1"><b>Ürün İçeriği:</b> {{urun.product.description|safe}}</p>
					<hr>
				{% endfor %}
			</div>
			</div>
			
			<div class = "oklar">
			  {% if onceki_siparis %}
				<p class = "text-right"><a href="{{onceki_siparis.get_absolute_url}}" class="btn btn-success" role="button">{{onceki_siparis.first_name}} {{onceki_siparis.last_name}} <i class ="fas fa-angle-double-right"></i></a></p>
			  {% endif %}
			  {% if sonraki_siparis %}
				<p class = "text-left"><a href="{{sonraki_siparis.get_absolute_url}}" class="btn btn-success" role="button"><i class ="fas fa-angle-double-left"></i> {{sonraki_siparis.first_name}} {{sonraki_siparis.last_name}} </a></p>
			  {% endif %}					
			</div>
		</div>
	</div>

{% endblock %}

orders/templates/orders/order/siparislerim.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Siparişlerim
{% endblock %}

{% block content %}
{% include 'includes/messages.html' %}
{% if siparisler %}
<h2 class = "text-center bg-info text-white py-1 siparis-basligi">Siparişlerim</h2>
{% for siparis in siparisler %}
<table class="table table-sm table-hover table-bordered table-responsive-sm siparis-tablo">
  <thead class ="bg-warning text-left">
    <tr class = "table-primary">
      <th scope="col">Sipariş- {{forloop.counter}} Bigileri</th>
	  <th scope="col">Değer</th>
    </tr>
  </thead>
  <tbody class = "table-success">
  
  <tr>
    <td>Sipariş Numarası:</td>
<td>{{siparis.get_siparis_no}}</td>  </tr>
  <tr>
    <td>Siparişte Son Durum:</td>
<td class = "text-danger">{{siparis.get_siparis_durumu_display}}</td>  </tr>
  <tr>
    <td>Tarih:</td>
<td>{{siparis.created}}</td>  </tr>
  <tr>
    <td>Ödeme Tercihiniz:</td>
<td>{{siparis.get_kargo_tipi_display}}</td>  </tr>
   <tr>
    <td>Sipariş Notunuz</td>
<td>{{siparis.siparis_notu}}</td>  </tr>
  
  {% for urun in siparis.orderitem_set.all %}  
  <tr>
    <td>{{urun.quantity}} set {{ urun.product.name }} tutarı:</td>
    <td>{{ urun.get_cost }} TL</td>
  </tr>

{% endfor %}
	
  <tr>
    <td>Ürünlerin Toplam Fiyatı:</b></td>
    <td colspan="num">{{ siparis.get_total_cost }} TL</td>
  </tr>
  <tr>
    <td>Kargo Ücreti:</b></td>
    <td colspan="num">{{ siparis.get_total_kargo }} TL</td>
  </tr>
    <tr>
    <td>Toplam:</td>
	<td class = "text-danger">{% if siparis.indirim_tutari > 0 %} <s>{{ siparis.get_total_bedel }} TL</s> <b>{{siparis.get_indirimli_bedel}} TL</b> {% else %} <b>{{ siparis.get_total_bedel }} TL</b> {% endif %}</td>
  </tr>
  
  </tbody>
</table>

{% endfor %}
{% else %}
<p> Üye olarak gerçekleştirdiğiniz bir sipariş bulunmamaktadır.</p>
{% endif %}

{% endblock %}



 
  

orders/templates/orders/order/siparislerin_hepsi.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Tüm Siparişler
{% endblock %}

{% block content %}
<a class = "btn btn-block btn-primary" href = "{% url 'orders:istatistikler' %}"> Satış Verileri</a>
<div class = "row justify-content-md-center">
	<div class = "col-md-8">
		<h1 class = "text-center text-info py-0 mb-0">Tüm Siparişler</h1>
		
		 <div class="btn-group btn-group-sm justify-content-between w-100 mb-2" role="group" aria-label="Basic example">
			<a href = "{% url 'orders:siparislerin_hepsi'%}" type="button" class="btn btn-primary">Hepsi</a>
			<a href = "{% url 'orders:siparislerin_hepsi_filtre' 1 %}" type="button" class="btn btn-danger">İşlemde</a>
			<a href = "{% url 'orders:siparislerin_hepsi_filtre' 2 %}" type="button" class="btn btn-warning">Hazırlanıyor</a>
			<a href = "{% url 'orders:siparislerin_hepsi_filtre' 3 %}" type="button" class="btn btn-success">Kargoda</a>
			<a href = "{% url 'orders:siparislerin_hepsi_filtre' 4 %}" type="button" class="btn btn-secondary">İptal</a>

		</div>

		<form class="form-inline justify-content-md-center form-sm">
			<div class="form-group mx-sm-3 mb-2">
			<label for="inputPassword2" class="sr-only">Sipariş</label>
			  <input type="text" class="form-control form-control-sm" id="inputPassword2" placeholder="İsim" name ="q">
			</div>
			<button type="submit" class="btn btn-primary btn-sm mb-2">Ara</button>
		  </form>
		<div class="card-body">
			<div class="list-group">
			{% for siparis in siparisler %}
			  <a href="{{siparis.get_absolute_url}}" class="list-group-item list-group-item-action list-group-item-info">{{ forloop.revcounter }}. {{siparis.first_name}} {{siparis.last_name}} - 
				<span class = "badge badge-pill {% if siparis.siparis_durumu == '1' %} badge-danger {% endif %} {% if siparis.siparis_durumu == '2' %} badge-warning {% endif %} {% if siparis.siparis_durumu == '4' %} badge-secondary {%endif%} {% if siparis.siparis_durumu == '3' %} badge-success {%endif%}">{{siparis.get_siparis_durumu_display}}-{{siparis.created|timesince}} önce</span>
			  </a>
			{% endfor %}
			</div>
		</div>
	</div>
</div>


{% endblock %}