anasayfa/urls.py
from django.urls import path

from . import views

app_name = 'anasayfa'
urlpatterns = [
    path('', views.AnaSayfa.as_view(), name='anasayfa'),
    path('ziyaretci-defteri/', views.ZiyaretView.as_view(), name='ziyaret'),
    path('yasal-uyarı/', views.YasalView.as_view(), name='copyright'),
    path('dokumanlar/', views.DokumanListView.as_view(), name='dokumanlar'),
    path('iletisim/', views.IletisimView.as_view(), name='iletisim'),
    path('cok-satanlar/', views.cok_satanlar, name='cok_satanlar'),
    #path('deneme/', views.deneme, name='deneme'),
    #path('dokumanlar/<slug:slug>/.docx/', views.DokumanListView.as_view(), name='dokuman-detail'),
    path('genel/<slug:slug>/', views.GenelDetailView.as_view(), name='genel-detail'),
    #path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    #path('<int:question_id>/vote/', views.vote, name='vote'),
]

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

kitap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap

from orders.views import load_cities

from accounts.views import TeacherSignUpView, UserUpdateView, SignUpView, UyelikView
from anasayfa.sitemaps import AnaCategorySitemap, ProductSitemap, StaticViewSitemap, GenelSitemap

sitemaps = {
	'kategoriler' : AnaCategorySitemap,
	'urunler': ProductSitemap,
	'statikler': StaticViewSitemap,
	'genel': GenelSitemap,
}

handler404 = 'anasayfa.views.view_404'

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('anasayfa.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    #path('accounts/signup/student/', StudentSignUpView.as_view(), name='student_signup'),
    path('accounts/signup/teacher/', TeacherSignUpView.as_view(), name='teacher_signup'),
	#path('accounts/turnuva/', turnuva, name='turnuva'),
	
	path('google68c54442c46469eb.html', TemplateView.as_view(template_name="google68c54442c46469eb.html")),
	#path('t4qt79m922kcpzkf7tuwn3mmebsdva.html', TemplateView.as_view(template_name="t4qt79m922kcpzkf7tuwn3mmebsdva.html")),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", content_type ="text/plain")),
	path('sitemap.xml/', sitemap, {'sitemaps':sitemaps}),
	
	
	path('uyelik/', UyelikView.as_view(), name = 'uyelik'),
	path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),
		
	url(r'^settings/account/$', UserUpdateView.as_view(), name='my_account'),
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),
        name='password_change_done'),
	
	path('ajax/load-cities/', load_cities, name='ajax_load_cities'),  # <-- this one here
	
	path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('shop/', include('shop.urls')),
	path('mesaj/', include('mesaj.urls')),
	
	
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mesaj/urls.py
from django.urls import path
from . import views

app_name = 'mesaj'

urlpatterns = [
   	path('mesajlar/', views.mesajlar, name='mesajlar'),
	path('mesajlar/create', views.create, name='mesaj-create'),
	#path('mesajlar/<int:id>/', views.detail, name='mesaj-detail'),
	path('mesajlar/<int:id>/update', views.update, name='mesaj-update'),
	path('mesajlar/<int:id>/delete', views.sil, name='mesaj-delete'),
]

orders/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
	url(r'^siparislerim/$', views.siparislerim, name='siparisler'),
	path('tarih/', views.tarih, name='tarih'),
	url(r'^siparisler/$', views.tum_siparisler, name='siparislerin_hepsi'),
	path('siparisler/<int:sayi>/', views.tum_siparisler_filtre, name='siparislerin_hepsi_filtre'),
	path('istatistikler/', views.istatistikler, name='istatistikler'),
	path('istatistikler/<int:gun>/', views.istatistik, name='istatistik'),
	url(r'^siparis-ekle/$', views.siparis_ekle, name='siparis-ekle'),
	path('<int:id>/siparisi-duzenle/', views.siparis_duzenle, name="siparis-duzenle"),
	path('<int:id>/', views.siparis_detail, name="siparis-detail"),
	path('<int:id>/urun-ekle/', views.siparis_detail_urun_ekle, name="siparis-detail-urun-ekle"),
	
]

shop/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
	path('<str:sayi>/', views.product_filter_list, name="product_list__filter"),
    url(r'^kategoriler/(?P<category_slug>[-\w]+)/$', views.category_product_list, name='product_list_by_category'),
	path('kategoriler/<slug:category_slug>/<str:sayi>/', views.category_product_filter_list, name="product_list__filter_by_category"),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/nasil-uygulanir/$', views.product_detail_nasil_uygulanir, name='nasil'),
]

templates/account_activation_invalid.html
There is an invalid account_activation_invalid.html

templates/account_information.html
Please confirm your mail adress

templates/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Kitap Turnuvası{% endblock %}</title>
	{% block metalar %}
		<meta name="description" content="Kitap Turnuvası; Öğrencileri Kitap Okumaya Teşvik Amaçlı Sayfa ve Gün Hedefli Kitap Takip Setleri ve Okuma Takip Ödülleri Müşteri İle Buluşturan Sitedir.">
		<meta name="keywords" content="Kitap Okuma Turnuvaları, Madalyalar">
	{% endblock %}
  <meta name="google-site-verification" content="Mb0Gkl_U9F1OLnHbqmYKcvq1Y8r7CC15k0pYRpbHt9E" />
  {% block sharethis%}
  {% endblock %}
  <!-- Global site tag (gtag.js) - Google Analytics --> 
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-178552468-1"> </script> 
  <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'UA-178552468-1'); </script>

    <!-- Global site tag (gtag.js) - Google Ads: 588387166 -->
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-588387166"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-588387166');
</script>

<!-- Event snippet for Website traffic conversion page -->
<script>
  gtag('event', 'conversion', {'send_to': 'AW-588387166/CtO_CLmE1eABEN6myJgC'});
</script>


	<link rel="shortcut icon" href="{% static 'img/favicon1.ico'%}" />
	<link rel="stylesheet" href="{% static 'css/all.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap9.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
	
	{% block stylesheet %}{% endblock %}
  </head>
  
 
  <body>
    {% block body %}
	<div class = "content">
	<nav class="navbar navbar-light bg-light py-0">
		<span class="navbar-text py-0">
    <small><b>Kitap Okuma Etkinlikleri</b></small>
		</span>
		
		<span class="navbar-text">
    <i class="fab fa-whatsapp"> <small>0505 763 63 81</small></i>
		</span>
	</nav>

      <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
        <div class="container-fluid text-white">
		  
          
			<a class="navbar-brand" href="{% url 'anasayfa:anasayfa' %}"><i class="fas fa-book-reader my-0 py-0"></i> Kitap Turnuvası</a>
			
			 
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="mainMenu">
		  
		    <ul class="navbar-nav ml-auto">
				{% if user.is_superuser %}
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'orders:siparislerin_hepsi' %}">Tüm siparişler</a>
				</li>
				
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'mesaj:mesajlar' %}">Mesajlaşma</a>
				</li>
				{% endif %}
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'anasayfa:dokumanlar' %}"><i class="fas fa-file-download"></i> Dokümanlar</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'anasayfa:ziyaret' %}"><i class="far fa-comment-alt"></i> Ziyaretçi Defteri</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'anasayfa:iletisim' %}"> <i class = "fas fa-map-marker-alt"></i> İletişim</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'shop:product_list' %}"><i class = "fas fa-store"></i> Mağaza</a>
				</li>
            {% if user.is_authenticated %}

                <li class="nav-item dropdown active">
                  <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   <i class = "fas fa-chalkboard-teacher"></i> {{ user.username }}
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
					<a class="dropdown-item" href="{% url 'orders:siparisler' %}">Siparişlerim</a>
                    <a class="dropdown-item" href="{% url 'my_account' %}">Hesabım</a>
                    <a class="dropdown-item" href="{% url 'password_change' %}">Şifre Değiştir</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}">Çıkış Yap</a>
                  </div>
                </li>
              </ul>
            {% else %}
			<!--  -->
              <form class="form-inline ml-auto">
				<a href="{% url 'login' %}" class="btn btn-outline-warning">Giriş Yap</a>
                <a href="{% url 'teacher_signup' %}" class="btn btn-outline-light ml-2">Kayıt Ol</a>
              </form>
            {% endif %}
          </div>
        </div>
      </nav>
	  
 

      <div class="container">
    <div class="row justify-content-end mr-1 mt-1 mb-2">
         <button class="btn btn-sm btn-info ">
            {% with totail_items=cart|length %}
                {% if cart|length > 0 %}
                    <a href="{% url 'cart:cart_detail' %}" style="color: #ffffff">
                       <i class = "fas fa-shopping-cart"></i> {{ totail_items }} ürün, {{ cart.get_total_price }} tl
                    </a>
                    {% else %}
                    <i class = "fas fa-shopping-cart"></i> Sepetiniz boş!
                {% endif %}
            {% endwith %}
         </button>
    </div>
	

		
       
		
        {% block content %}
        {% endblock %}
		</div>
		</div>
		
		
      
		<footer class = "footer mt-1 mb-0">
		<ul class="list-unstyled list-inline text-center mb-0">
      <li class="list-inline-item">
        <a class="btn-floating btn-fb mx-1">
          <i class="fab fa-facebook-f"> </i>
        </a>
      </li>
      <li class="list-inline-item">
        <a class="btn-floating btn-tw mx-1">
          <i class="fab fa-twitter"> </i>
        </a>
      </li>
	  <li class="list-inline-item">
        <a class="btn-floating btn-tw mx-1">
          <i class="fab fa-instagram"></i>
        </a>
      </li>
    </ul>
	
	   <p class = "text-center mb-0"> © 2012 Tüm hakları saklıdır - <a href = "{% url 'anasayfa:copyright' %}" class = "text-white"> Kullanım Hakları</a> </p>
		</footer>	
	   
    {% endblock body %}	
    <script src="{% static 'js/jquery9.min.js' %}"></script>
    <script src="{% static 'js/popper9.min.js' %}"></script>
    <script src="{% static 'js/bootstrap9.min.js' %}"></script>
	{% block javascript %}{% endblock %}
  </body>
</html>

templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'anasayfa:anasayfa' %}">Kitap Turnuvası</a>
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

templates/board.html
{% extends 'base.html' %}

{% load humanize %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Forum</li>
{% endblock %}

{% block content %}
  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Ana Başlıklar</th>
        <th>Mesajlar</th>
        <th>Alt Başlıklar</th>
        <th>Son Mesaj</th>
      </tr>
    </thead>
    <tbody>
      {% for board in boards %}
        <tr>
          <td>
            <a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a>
            <small class="text-muted d-block">{{ board.description }}</small>
          </td>
          <td class="align-middle">
            {{ board.get_posts_count }}
          </td>
          <td class="align-middle">
            {{ board.topics.count }}
          </td>
          <td class="align-middle">
            {% with post=board.get_last_post %}
              {% if post %}
                <small>
                  <a href="{% url 'topic_posts' board.pk post.topic.pk %}">
                    {{ post.created_by.username }} tarafından {{ post.created_at|naturaltime }}
                  </a>
                </small>
              {% else %}
                <small class="text-muted">
                  <em>Henüz bir mesaj gönderilmemiştir.</em>
                </small>
              {% endif %}
            {% endwith %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/google102aeaa3d2712612.html
google-site-verification: google102aeaa3d2712612.html

templates/google68c54442c46469eb.html
google-site-verification: google68c54442c46469eb.html

templates/login.html
{% extends 'base_accounts.html' %}

{% block title %}Log in to Django Boards{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-5 col-md-7 col-sm-8">
      <div class="card card-arka-plan">
        <div class="card-body">
          <h3 class="card-title">Giriş Yap</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            {% include 'includes/form2.html' %}			
            <button type="submit" class="btn btn-primary btn-block">Giriş</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          Üye değilseniz? <a href="{% url 'teacher_signup' %}">Üye olun</a>
        </div>
      </div>      
    </div>
  </div>
{% endblock %}

templates/new_topic.html
{% extends 'base.html' %}

{% block title %}Start a New Topic{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topics' board.pk %}">{{ board.name }}</a></li>
  <li class="breadcrumb-item active">New topic</li>
{% endblock %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Post</button>
  </form>
{% endblock %}

templates/password_change.html
{% extends 'base.html' %}

{% block title %}Şifreyi Güncelle{% endblock %}


  <li class="breadcrumb-item active">Şifreyi Güncelle</li>


{% block content %}
  <div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form2.html' %}
        <button type="submit" class="btn btn-success">Güncelle</button>
      </form>
    </div>
  </div>
{% endblock %}

templates/password_reset.html
{% extends 'base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Şifrenizi değiştirin</h3>
          <p>Lütfen e-mail adresinizi giriniz. Şifrenizi yenileyebilmeniz için bir link gönderilecektir. </p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form2.html' %}
            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/signup.html
{% extends 'base_accounts.html' %}

{% block title %}Sign up to Django Boards{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8 col-md-10 col-sm-12">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Sign up</h3>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Create an account</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          Already have an account? <a href="{% url 'login' %}">Log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/t4qt79m922kcpzkf7tuwn3mmebsdva.html
t4qt79m922kcpzkf7tuwn3mmebsdva

templates/topic_posts.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ topic.subject }}{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Forum</a></li>
  <li class="breadcrumb-item"><a href="{% url 'board_topics' topic.board.pk %}">{{ topic.board.name }}</a></li>
  <li class="breadcrumb-item active">{{ topic.subject }}</li>
{% endblock %}

{% block content %}

  <div class="mb-4">
    <a href="{% url 'reply_topic' topic.board.pk topic.pk %}" class="btn btn-primary" role="button">Cevapla</a>
  </div>

  {% for post in posts %}
    <div id="{{ post.pk }}" class="card {% if forloop.last %}mb-4{% else %}mb-2{% endif %} {% if forloop.first %}border-dark{% endif %}">
      {% if forloop.first %}
        <div class="card-header text-white bg-dark py-2 px-3">{{ topic.subject }}</div>
      {% endif %}
      <div class="card-body p-3">
        <div class="row">
          <div class="col-2">
            <img src="{% static 'avatar.png' %}" alt="{{ post.created_by.username }}" class="w-100 rounded">
            <small>Posts: {{ post.created_by.posts.count }}</small>
          </div>
          <div class="col-10">
            <div class="row mb-3">
              <div class="col-6">
                <strong class="text-muted">{{ post.created_by.username }}</strong>
              </div>
              <div class="col-6 text-right">
			  
                <small class="text-muted">{{ post.created_at }}</small>
              </div>
			  <div class = "col-12">
			  {% if post.image %}
			     <img src="{{post.image.url}}" class="img-fluid img-thumbnail mb-2" alt="Resim">
			  {% endif %}
				<p>{{post.message|safe}}</p>
			  </div>
            </div>
            {% if post.created_by == user %}
              <div class="mt-3">
                <a href="{% url 'edit_post' post.topic.board.pk post.topic.pk post.pk %}"
                   class="btn btn-primary btn-sm"
                   role="button">Düzenle</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}

  {% include 'includes/pagination.html' %}

{% endblock %}